// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vev.Atlas.Persistence;

#nullable disable

namespace Vev.Atlas.Persistence.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260817103803_AddAssetCreatedBy")]
    partial class AddAssetCreatedBy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Vev.Atlas.Persistence.AiModuleSettingsRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsentAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ConsentAcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsentAcceptedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("ai_module_settings", (string)null);
                });

            modelBuilder.Entity("Vev.Atlas.Persistence.AssetRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("NumericId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Kind");

                    b.HasIndex("TenantId", "NumericId")
                        .IsUnique();

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Vev.Atlas.Persistence.RelationshipRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "FromId");

                    b.ToTable("relationships", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
