// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vev.Atlas.Persistence;

#nullable disable

namespace Vev.Atlas.Persistence.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20261002180123_AddConnectedConsumers")]
    partial class AddConnectedConsumers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Vev.Atlas.Persistence.AiModuleSettingsRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsentAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ConsentAcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsentAcceptedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("ai_module_settings", (string)null);
                });

            modelBuilder.Entity("Vev.Atlas.Persistence.AssetRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("NumericId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Kind");

                    b.HasIndex("TenantId", "NumericId")
                        .IsUnique();

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Vev.Atlas.Persistence.ConnectedConsumerRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CredentialExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KindsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastContentFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSuccessSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedCredential")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("State");

                    b.ToTable("connected_consumers", (string)null);
                });

            modelBuilder.Entity("Vev.Atlas.Persistence.DigestKeyRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedPrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeySpki")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("digest_key", (string)null);
                });

            modelBuilder.Entity("Vev.Atlas.Persistence.DigestStateRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("digest_state", (string)null);
                });

            modelBuilder.Entity("Vev.Atlas.Persistence.RelationshipRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "FromId");

                    b.ToTable("relationships", (string)null);
                });

            modelBuilder.Entity("Vev.Atlas.Persistence.TargetVersionRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "Id");

                    b.ToTable("target_versions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
